# Automatically generated by GPRPy
import gprpy.gprpy as gp
mygpr = gp.gprpyProfile()
mygpr.importdata('DuneData.DZT')
mygpr.setZeroTime(5)
mygpr.dewow(999999)
mygpr.remMeanTrace(999999)
mygpr.setVelocity(0.14)
mygpr.fkMigration()
mygpr.topoCorrect('DuneTopo.txt',delimiter='\t')
mygpr.printProfile('DuneFig.pdf', color='bwr',
                   contrast=6, yrng=[16.5,19.7],
                   xrng=[0,20.8], asp=2, dpi=600)
mygpr.exportVTK('/home/alainplattner/Desktop/research/GPR/DuneOfPilat/Spring2017/Grid2/Line27p',gpsinfo=mygpr.threeD,thickness=0,delimiter='\t',aspect=1,smooth=True, win_length=51, porder=3)
