# Automatically generated by GPRPy
import gprpy.gprpy as gp
mygpr = gp.gprpyProfile()
mygpr.importdata('YosemiteData.DT1')
mygpr.setZeroTime(2.5)
mygpr.alignTraces()
mygpr.dewow(99999)
mygpr.remMeanTrace(99999)
mygpr.smooth(10)
mygpr.tpowGain(1.2)
mygpr.setVelocity(0.1)
mygpr.fkMigration()
mygpr.profileSmooth(6,4)
mygpr.topoCorrect('YosemiteTopo.txt')
mygpr.printProfile('YosemiteFig.pdf', color='bwr',
                   contrast=3, yrng=[1195,1225],
                   xrng=[0,323.088], asp=2, dpi=300)
