# Automatically generated by GPRPy
import gprpy.gprpy as gp
mygpr = gp.gprpyCW()
mygpr.importdata('WARRData.DT1',dtype='WARR')
mygpr.setZeroTime(34)
mygpr.truncateY(200)
mygpr.dewow(999999)
mygpr.normalize()
mygpr.linStackedAmplitude(vmin=0.01,vmax=0.31,vint=0.001)
mygpr.hypStackedAmplitude(vmin=0.01,vmax=0.31,vint=0.001)
mygpr.addLin(zerotwtt=0,vel=0.3)
mygpr.addLin(zerotwtt=0.1,vel=0.1)
mygpr.addHyp(zerotwtt=89,vel=0.1)
mygpr.printCWFigure('WARRFigs_data.pdf', color='gray',
                    contrast=5, yrng=[199.615,0.07],
                    xrng=[0.6,16.3], showlnhp=True, dpi=600)
mygpr.printStAmpFigure('WARRFigs_linSemb.pdf', whichstamp='lin',
                      saturation=1.5, yrng=[199.615,0.07],
                      vrng=[0.01,0.31])
mygpr.printStAmpFigure('WARRFigs_hypSemb.pdf', whichstamp='hyp',
                      saturation=1.5, yrng=[199.615,0.07],
                      vrng=[0.01,0.31])
