// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// kirMigTopo_cpp
NumericMatrix kirMigTopo_cpp(const NumericMatrix& x, const NumericVector& tx_x, const NumericVector& tx_z, const NumericVector& rx_x, const NumericVector& rx_z, const NumericVector& wq, const NumericVector& xout, const NumericVector& surface, const NumericVector& zout, double dz, double dts, double v, double max_depth, bool use_fresnel, double lambda, double max_angle, int weight_type, bool spreading, bool normalize, bool antialias, double aa_factor);
RcppExport SEXP _RGPR_kirMigTopo_cpp(SEXP xSEXP, SEXP tx_xSEXP, SEXP tx_zSEXP, SEXP rx_xSEXP, SEXP rx_zSEXP, SEXP wqSEXP, SEXP xoutSEXP, SEXP surfaceSEXP, SEXP zoutSEXP, SEXP dzSEXP, SEXP dtsSEXP, SEXP vSEXP, SEXP max_depthSEXP, SEXP use_fresnelSEXP, SEXP lambdaSEXP, SEXP max_angleSEXP, SEXP weight_typeSEXP, SEXP spreadingSEXP, SEXP normalizeSEXP, SEXP antialiasSEXP, SEXP aa_factorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type tx_x(tx_xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type tx_z(tx_zSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type rx_x(rx_xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type rx_z(rx_zSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type wq(wqSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type xout(xoutSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type surface(surfaceSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type zout(zoutSEXP);
    Rcpp::traits::input_parameter< double >::type dz(dzSEXP);
    Rcpp::traits::input_parameter< double >::type dts(dtsSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< double >::type max_depth(max_depthSEXP);
    Rcpp::traits::input_parameter< bool >::type use_fresnel(use_fresnelSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type max_angle(max_angleSEXP);
    Rcpp::traits::input_parameter< int >::type weight_type(weight_typeSEXP);
    Rcpp::traits::input_parameter< bool >::type spreading(spreadingSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    Rcpp::traits::input_parameter< bool >::type antialias(antialiasSEXP);
    Rcpp::traits::input_parameter< double >::type aa_factor(aa_factorSEXP);
    rcpp_result_gen = Rcpp::wrap(kirMigTopo_cpp(x, tx_x, tx_z, rx_x, rx_z, wq, xout, surface, zout, dz, dts, v, max_depth, use_fresnel, lambda, max_angle, weight_type, spreading, normalize, antialias, aa_factor));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RGPR_kirMigTopo_cpp", (DL_FUNC) &_RGPR_kirMigTopo_cpp, 21},
    {NULL, NULL, 0}
};

RcppExport void R_init_RGPR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
