// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <RcppThread.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// iradon_transform_fbp_rcpp
Eigen::MatrixXd iradon_transform_fbp_rcpp(const Eigen::MatrixXd& R, int N, int M, double delta_x, double theta_min, double theta_max, double rho_min_in, double delta_rho_in, const std::string& filter, const std::string& normalization);
RcppExport SEXP _RGPR_iradon_transform_fbp_rcpp(SEXP RSEXP, SEXP NSEXP, SEXP MSEXP, SEXP delta_xSEXP, SEXP theta_minSEXP, SEXP theta_maxSEXP, SEXP rho_min_inSEXP, SEXP delta_rho_inSEXP, SEXP filterSEXP, SEXP normalizationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type R(RSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< double >::type delta_x(delta_xSEXP);
    Rcpp::traits::input_parameter< double >::type theta_min(theta_minSEXP);
    Rcpp::traits::input_parameter< double >::type theta_max(theta_maxSEXP);
    Rcpp::traits::input_parameter< double >::type rho_min_in(rho_min_inSEXP);
    Rcpp::traits::input_parameter< double >::type delta_rho_in(delta_rho_inSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type filter(filterSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type normalization(normalizationSEXP);
    rcpp_result_gen = Rcpp::wrap(iradon_transform_fbp_rcpp(R, N, M, delta_x, theta_min, theta_max, rho_min_in, delta_rho_in, filter, normalization));
    return rcpp_result_gen;
END_RCPP
}
// radon_transform_rcpp
Eigen::MatrixXd radon_transform_rcpp(const Eigen::MatrixXd& A, int n_theta, int n_rho, double delta_x, double theta_min, double theta_max, double rho_min_in, double delta_rho_in, bool linear_interp, int normalization);
RcppExport SEXP _RGPR_radon_transform_rcpp(SEXP ASEXP, SEXP n_thetaSEXP, SEXP n_rhoSEXP, SEXP delta_xSEXP, SEXP theta_minSEXP, SEXP theta_maxSEXP, SEXP rho_min_inSEXP, SEXP delta_rho_inSEXP, SEXP linear_interpSEXP, SEXP normalizationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type A(ASEXP);
    Rcpp::traits::input_parameter< int >::type n_theta(n_thetaSEXP);
    Rcpp::traits::input_parameter< int >::type n_rho(n_rhoSEXP);
    Rcpp::traits::input_parameter< double >::type delta_x(delta_xSEXP);
    Rcpp::traits::input_parameter< double >::type theta_min(theta_minSEXP);
    Rcpp::traits::input_parameter< double >::type theta_max(theta_maxSEXP);
    Rcpp::traits::input_parameter< double >::type rho_min_in(rho_min_inSEXP);
    Rcpp::traits::input_parameter< double >::type delta_rho_in(delta_rho_inSEXP);
    Rcpp::traits::input_parameter< bool >::type linear_interp(linear_interpSEXP);
    Rcpp::traits::input_parameter< int >::type normalization(normalizationSEXP);
    rcpp_result_gen = Rcpp::wrap(radon_transform_rcpp(A, n_theta, n_rho, delta_x, theta_min, theta_max, rho_min_in, delta_rho_in, linear_interp, normalization));
    return rcpp_result_gen;
END_RCPP
}
// test_phantom_projection
Eigen::MatrixXd test_phantom_projection(int size);
RcppExport SEXP _RGPR_test_phantom_projection(SEXP sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(test_phantom_projection(size));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RGPR_iradon_transform_fbp_rcpp", (DL_FUNC) &_RGPR_iradon_transform_fbp_rcpp, 10},
    {"_RGPR_radon_transform_rcpp", (DL_FUNC) &_RGPR_radon_transform_rcpp, 10},
    {"_RGPR_test_phantom_projection", (DL_FUNC) &_RGPR_test_phantom_projection, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_RGPR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
