# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kirMigTopoConst_cpp <- function(x, tx_x, tx_z, rx_x, rx_z, wq, xout, surface, zout, dz, dts, v, max_depth, use_fresnel, lambda, max_angle, weight_type, spreading, normalize, antialias, aa_factor) {
    .Call('_RGPR_kirMigTopoConst_cpp', PACKAGE = 'RGPR', x, tx_x, tx_z, rx_x, rx_z, wq, xout, surface, zout, dz, dts, v, max_depth, use_fresnel, lambda, max_angle, weight_type, spreading, normalize, antialias, aa_factor)
}

kirMigTopoVar_cpp <- function(x, tx_x, tx_z, rx_x, rx_z, wq, xout, surface, zout, dz, dts, max_depth, use_fresnel, lambda_per_v, max_angle, weight_type, spreading, normalize, antialias, aa_factor, vel_mode, cum, slow, xv0, dxv, ray_step, n_ray_max) {
    .Call('_RGPR_kirMigTopoVar_cpp', PACKAGE = 'RGPR', x, tx_x, tx_z, rx_x, rx_z, wq, xout, surface, zout, dz, dts, max_depth, use_fresnel, lambda_per_v, max_angle, weight_type, spreading, normalize, antialias, aa_factor, vel_mode, cum, slow, xv0, dxv, ray_step, n_ray_max)
}

