# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kirMigTopo_cpp <- function(x, tx_x, tx_z, rx_x, rx_z, wq, xout, surface, zout, dz, dts, v, max_depth, use_fresnel, lambda, max_angle, weight_type, spreading, normalize, antialias, aa_factor) {
    .Call('_RGPR_kirMigTopo_cpp', PACKAGE = 'RGPR', x, tx_x, tx_z, rx_x, rx_z, wq, xout, surface, zout, dz, dts, v, max_depth, use_fresnel, lambda, max_angle, weight_type, spreading, normalize, antialias, aa_factor)
}

