# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

iradon_transform_fbp_rcpp <- function(R, N, M, delta_x = 1.0, theta_min = 0.0, theta_max, rho_min_in, delta_rho_in, filter = "ramp", normalization = "none") {
    .Call('_RGPR_iradon_transform_fbp_rcpp', PACKAGE = 'RGPR', R, N, M, delta_x, theta_min, theta_max, rho_min_in, delta_rho_in, filter, normalization)
}

radon_transform_rcpp <- function(A, n_theta = 180L, n_rho = 0L, delta_x = 1.0, theta_min = 0.0, theta_max, rho_min_in, delta_rho_in, linear_interp = TRUE, normalization = 1L) {
    .Call('_RGPR_radon_transform_rcpp', PACKAGE = 'RGPR', A, n_theta, n_rho, delta_x, theta_min, theta_max, rho_min_in, delta_rho_in, linear_interp, normalization)
}

test_phantom_projection <- function(size = 64L) {
    .Call('_RGPR_test_phantom_projection', PACKAGE = 'RGPR', size)
}

